Simplify Raindrops tests
By using simple Groovy assertions, we

- remove references to JUnit, which may confuse non-Java folk
- make the tests fit onto a single page, improving readability
- use Groovy's native power `assert`, making the tests more idiomatic
- remove the need to comment/ignore tests to practice TDD
  (the first test to fail outputs and halts)

But the primary motivator for me was to make the output clearer.

The second failure under JUnit tests reads something like:

```
] groovy RaindropsTest.groovy
JUnit 4 Runner, Tests: 16, Failures: 13, Time: 59
Test Failure: test105(RaindropsTest)
org.junit.ComparisonFailure: expected:<[PlingPlangPlong]> but was:<[105]>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.junit.Assert.assertEquals(Assert.java:144)
```
...several dozen stacktrace lines, which tend to scroll.

Power assert outputs:

```
] groovy RaindropsTest.groovy
assert raindrops.convert(3)     == 'Pling'
       |         |              |
       |         3              false
       Raindrops@c267ef4
]
```